[tool.poetry]
name = "fluid-sbom"
version = "1.0.1"
description = ""
authors = ["Fluid Attacks <development@fluidattacks.com>"]

[tool.poetry.dependencies]
python = "^3.11"
beautifulsoup4 = "4.12.3"
boto3 = "1.34.106"
boto3-stubs = {"extras" = ["s3"], version = "1.34.160"}
bugsnag = "4.7.1"
click = "8.1.7"
cpe = "1.3.0"
cyclonedx-python-lib= { extras = ["json-validation", "validation", "xml-validation"], version = "7.3.4" }
diskcache = "^5.6.3"
diskcache-stubs = "5.6.3.5.20240619"
furl = "2.1.3"
more-itertools = "10.3.0"
os-release = "1.0.1"
phpserialize = "1.3"
platformdirs = "^4.2.2"
pydantic = "^2.8.2"
reactivex = "4.0.4"
redis = "^5.0.7"
requests = "2.32.3"
requirements-parser = "0.9.0"
semver = "3.0.2"
spdx-lookup= "0.3.3"
spdx-matcher = "0.0.13"
spdx-tools= "0.8.2"
tomlkit = "^0.12.4"
tqdm = "4.66.5"
tree-sitter = "0.21.3"
types-jsonschema = "4.23.0.20240813"
types-requests = "2.31.0.20240406"
types-tqdm = "4.66.0.20240417"
versio = "0.5.0"

[tool.poetry.group.dev.dependencies]
pytest = "8.1.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
