[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
[project]
name = "taxi_data_core"
version = "0.0.8"
authors = [
  { name="Wayne Bennett", email="wayne.bennett@live.com" },
]
description = "Core modules for taxi_data funcitonality."
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/WayneBennett666/taxi-data_core"
Issues = "https://github.com/WayneBennett666/taxi-data_core/issues"
