[tool.poetry]
name = "plurally"
version = "0.1.7"
description = ""
authors = ["Alexandre Villard <alexvillard67@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
loguru = "^0.7.2"
networkx = {extras = ["default"], version = "^3.3"}
pydantic = "^2.8.2"
instructor = "^1.4.0"
cryptography = "^43.0.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.2"
pre-commit = "^3.8.0"
ruff = "^0.6.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
