[tool.poetry]
name = "lockss-turtles"
version = "0.5.0-dev3"
description = "Tool to manage LOCKSS plugin sets and LOCKSS plugin registries"
license = "BSD-3-Clause"
authors = [
    "Thib Guicherd-Callin <thib@cs.stanford.edu>"
]
readme = "README.rst"
homepage = "https://www.lockss.org/"
repository = "https://github.com/lockss/lockss-turtles"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Intended Audience :: System Administrators",
    "Operating System :: POSIX :: Linux",
    "Topic :: Utilities"
]
packages = [
    { include = "lockss", from = "src" }
]
include = [
    "CHANGELOG.rst"
]

[tool.poetry.dependencies]
python = "^3.8"
java-manifest = "^1.1.0"
jsonschema = "^4.23.0"
pyyaml = "^6.0.2"
rich-argparse = "^1.5.2"
tabulate = "^0.9.0"
xdg = "^6.0.0"

[tool.poetry.scripts]
turtles = 'lockss.turtles.cli:main'

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
