[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "hierarchical-label-propagation"
version = "0.1.0"
authors = [{ name = "Ludovic TUNCAY", email = "ludovic.tuncay@irit.fr" }]
description = "Python implementation of Hierarchical Label Propagation (HLP)"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
keywords = [
    "Hierarchical Label Propagation",
    "HLP",
    "Ontology",
    "Hierarchy",
]
dependencies = [
    "torch>=1.8.0",
]

[project.urls]
Homepage = "https://github.com/LudovicTuncay/hierarchical-label-propagation"
Issues = "https://github.com/LudovicTuncay/hierarchical-label-propagation/issues"

[tool.hatch.build.targets.wheel]
packages = ["src/hierarchical_label_propagation"]

[tool.hatch.build.targets.sdist]
include = [
    "/src",
    "/tests",
]