[package]
name = "mmio-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "m2io_tmp"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.22.0"
oca-rs = { version = "0.5.5" }
transformation-file = { version = "0.5.5" }
oca-bundle-semantics = { version = "0.5.5" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
polars = "0.42.0"
pyo3-polars = "0.16.1"
