[project]
name = "nonebot-plugin-werewolf"
version = "1.0.7"
description = "Default template for PDM package"
authors = [
    { name = "wyf7685", email = "wyf7685@163.com" },
]
dependencies = [
    "nonebot2>=2.3.3",
    "nonebot-plugin-alconna>=0.52.1",
    "nonebot-plugin-userinfo>=0.2.6",
    "nonebot-plugin-waiter>=0.7.1",
]
requires-python = ">=3.10"
readme = "README.md"

[project.license]
text = "MIT"

[build-system]
requires = [
    "pdm-backend",
]
build-backend = "pdm.backend"

[tool.pdm]
distribution = true

[tool.pdm.scripts]
updver = "pdm run python ./scripts/update_version.py"

[tool.pdm.scripts.lint]
composite = [
    "isort .",
    "black .",
    "pyright .",
    "ruff check .",
]

[tool.pdm.dev-dependencies]
dev = [
    "isort>=5.13.2",
    "black>=24.8.0",
    "ruff>=0.6.2",
    "pyright>=1.1.377",
    "nonebot2[fastapi]>=2.3.3",
    "nonebot-adapter-onebot>=2.4.4",
]

[tool.black]
line-length = 88
target-version = [
    "py310",
]
include = "\\.pyi?$"
extend-exclude = ""

[tool.isort]
profile = "black"
line_length = 88
skip_gitignore = true
src_paths = [
    "nonebot_plugin_werewolf",
]
extra_standard_library = [
    "typing_extensions",
]

[tool.ruff]
line-length = 88
target-version = "py310"

[tool.ruff.lint]
select = [
    "F",
    "W",
    "E",
    "UP",
    "ASYNC",
    "C4",
    "T10",
    "T20",
    "PYI",
    "PT",
    "Q",
    "RUF",
]
ignore = [
    "C408",
    "E402",
    "RUF001",
    "RUF002",
    "RUF003",
]

[tool.pyright]
pythonVersion = "3.10"
pythonPlatform = "All"
typeCheckingMode = "standard"
reportShadowedImports = false
disableBytesTypePromotions = true

[tool.nonebot]
adapters = [
    { name = "OneBot V11", module_name = "nonebot.adapters.onebot.v11" },
]
plugins = [
    "nonebot_plugin_werewolf",
]
plugin_dirs = []
builtin_plugins = []
