[tool.poetry]
name = "almanak"
version = "0.1.5"
description = "SDK for interacting with Almanak's Multiverse Platform"
authors = ["Engineering <engineering@almanak.co>"]
readme = "README.md"
packages = [
    { include = "almanak" }
]

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.31.0"
click = "^8.1.7"
pyjwt = "^2.8.0"
httpx = "^0.27.0"
anyio = "^4.3.0"
pydantic = "^2.7.1"
pandas = "^2.2.2"
hexbytes = "^1.2.1"
aiohttp = "^3.10.5"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.3"
coverage = "^7.3.2"
mock = "^5.1.0"
pylint = "^3.0.2"
isort = "^5.12.0"
bandit = "^1.7.5"
safety = "^2.3.5"
yapf = "^0.40.2"
pytest-mock = "^3.14.0"
pydoc-markdown = "^4.8.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.bandit.assert_used]
skips = ['*_test.py', '*/test_*.py']


[tool.bandit]
exclude_dirs = ["almanak/tests"]
tests = ["B201", "B301"]
skips = ["B101", "B601"]


[tool.pytest.ini_options]
addopts = "--import-mode=append -vv"
testpaths = [
    "almanak/tests"
]
pythonpath = ["almanak"]

