[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "nordpool-daily-averages"
version= "1.0.10"
description = "REST api wrapper for nordpool average daily spot prices api"
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.12"

dependencies = [
    "httpx"
]