[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
[project]
name = "gather_taxi_data"
version = "0.0.6"
authors = [
  { name="Wayne Bennett", email="wayne.bennett@live.com" },
]
description = "Export data from web portals and save to database."
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/WayneBennett666/gather-taxi-data"
Issues = "https://github.com/WayneBennett666/gather-taxi-data/issues"
