[tool.poetry]
name = "aixnet-beta"
version = "0.2.3"
description = "The official package of AI-X-Net."
authors = ["Yiqiao Yin <eagle0504@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.32.3"
openai = "^1.43.0"
azure-ai-inference = "^1.0.0b4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
