[package]
name = "gtdb_tree"
version = "0.1.8"
edition = "2021"
description = "A library for parsing Newick format files, especially GTDB tree files."
homepage = "https://github.com/eric9n/gtdb_tree"
repository = "https://github.com/eric9n/gtdb_tree"
keywords = ["Newick", "GTDB", "tree", "parser"]
license = "MIT"
authors = ["dagou <eric9n@gmail.com>"]

[lib]
name = "gtdb_tree"
crate-type = ["cdylib", "rlib"]


[dependencies]
memchr = "2.7.4"
pyo3 = { version = "0.22", optional = true, features = ["extension-module"] }


[features]
bindings = ["pyo3"]
python = ["pyo3"]

[build-dependencies]
pyo3-build-config = "0.22.0"
