[tool.poetry]
name = "certificate-check"
version = "1.3.0"
description = ""
authors = ["helio12242 <heliojorgesilva12@hotmail.com>"]
readme = "README.md"

[tool.poetry.scripts]
certificate-check = "certificate_check.main:app"

[tool.poetry.dependencies]
python = "^3.10"
typer = "^0.12.5"
requests = "^2.32.3"
cryptography = "^43.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
