[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "taxref"
version = "0.1.2"
authors = [
  { name="Samuel AndrÃ©s", email="samuel.andres@yahoo.fr" },
]
description = "A simple taxref toolbox."
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
keywords = ["taxref", "taxonomy"]

[project.urls]
"Homepage" = "https://github.com/SamuelAndresPascal/cosmoloj-py/tree/taxref_0.1.2/taxref"