[build-system]
build-backend = "poetry.masonry.api"
requires = ["poetry>=0.12"]

[tool.poetry]
authors = ["Lukas Karlsson <karlsson@broadinstitute.org>"]
description = "BITS MHL"
exclude = [
    "**/*.pyc",
    "**/*.pyi",
]
homepage = "https://github.com/broadinstitute/bits-mhl.git"
keywords = ["bits", "mhl"]
license = "BSD-3-Clause"
name = "bits-mhl"
packages = [
    { include = "bits" },
]
readme = "README.md"
repository = "https://github.com/broadinstitute/bits-mhl.git"
version = "1.21.4"

[tool.poetry.dependencies]
python = "^3.6"  # Compatible python versions must be declared here

netaddr = "<1.0.0"

[tool.poetry.dev-dependencies]
bump2version = "^1.0.1"
mock = "^5.1.0"
pyflakes = '<2.5.0'
pylama = "^7.7.1"
pytest = "^7.0.1"
pyyaml = "^6.0.1"
testtools = "^2.6.0"
twine = "^3.8.0"
yamllint = "^1.28.0"
