[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "php-version-compare"
dynamic = ["version"]
description = "PHP-compatible version comparison for Python"
readme = "README.md"
requires-python = ">=3.6"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Apache Software License",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3 :: Only",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
keywords = ["php", "version", "compare", "comparison", "compatibility"]
dependencies = [
    "typing-extensions; python_version < '3.8'",
]

[project.optional-dependencies]
dev = ["bump-my-version", "hatchling", "ruff", "tox"]
test = ["pytest", "pytest-cov", "pytest-randomly"]

[project.urls]
Repository = "https://github.com/marcfrederick/php-version-compare"
Issues = "https://github.com/marcfrederick/php-version-compare/issues"
Changelog = "https://github.com/marcfrederick/php-version-compare/releases"

[tool.hatch.version]
path = "src/php_version_compare/__init__.py"

[tool.hatch.build.targets.sdist]
exclude = ["tox.ini", "tests"]

[tool.bumpversion]
current_version = "1.0.1"
commit = true
tag = true
tag_name = "v{new_version}"
message = "Bump version: {current_version} â†’ {new_version}"

[[tool.bumpversion.files]]
filename = "src/php_version_compare/__init__.py"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-v --doctest-modules --cov=php_version_compare src tests"
testpaths = ["tests"]

[tool.pyright]
include = ["src/**/*.py", "tests/**/*.py"]
strict = ["*"]
extraPaths = ["src"]
pythonVersion = "3.6"
