[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "cbnumber"
version = "1.0"
authors = [
  { name="Jean MoÃ¯se Talec", email="jmtalec@gmail.com" },
]
description = "A module representing numbers in arbitrary bases, extending the built-in `int` type."
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/jmtalec/NumberBase"
Issues = "https://github.com/jmtalec/NumberBase/issues"