[build-system]
requires = [
  "setuptools>=61.0",
  "websocket",
  "toml"
  ]
build-backend = "setuptools.build_meta"

[project]
name = "orbitdb_kit_py"
version = "0.0.6"
authors = [
  { name="Benjamin Barber", email="starworks5@gmail.com" },
]
description = "a python wrapper around nodejs orbitdb"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU Affero General Public License v3 or later (AGPLv3+)",
    "Operating System :: POSIX :: Linux",
]
[project.urls]
Homepage = "https://github.com/endomorphosis/orbitdb_kit"
Issues = "https://github.com/endomorphosis/orbitdb_kit/issues"